name: clima
description: Weather app for android and IOS.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  geolocator: ^7.6.0
  http: ^0.13.3
  flutter_spinkit: ^5.1.0


dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/appicon.png"

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Spartan
      fonts:
        - asset: fonts/SpartanMB-Black.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
